---
name: replaceme.STACKNAME-${DOCK_ENVIRON}

services:
  app:
    image: replaceme.APPNAME:replaceme.VERSTAG
    container_name: ${COMPOSE_PROJECT_NAME}_APPNAME
    ports:
      - "${APPNAME_HOST_PORT}:${APPNAME_CONTAINER_PORT}"

networks:
  default:
    name: internal

volumes:
  app: